version: "3.9"

services:
  web:
    container_name: django_api
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.development
    volumes:
      - ./:/thnz/
      - static_volume:/thnz/static
      - media_volume:/thnz/media
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: django_db
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'django_db'
      MYSQL_PASSWORD: 'zpy3nmxa0k4sh4'
      MYSQL_ROOT_PASSWORD: 'zpy3nmxa0k4sh4'

    volumes:
      - db_data:/var/lib/mysql:rw

  nginx:
    container_name: django_nginx
    image: nginx:1.25.3-alpine
    ports:
      - 80:80
    volumes:
      - ./data/nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - static_volume:/thnz/static
      - media_volume:/thnz/media

volumes:
  db_data:
  static_volume:
  media_volume:
