version: "3.9"

services:
  web:
    container_name: django_api
    build: .
    command: daphne core.asgi:application --bind 0.0.0.0 --port 8000
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.production
    volumes:
      - ./:/asoud/
      - static_volume:/thnz/static
      - media_volume:/thnz/media
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - main_network

  db:
    container_name: django_db
    image: mysql:latest
    command: --max_connections=1000
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql:rw
    networks:
      - main_network

  nginx:
    container_name: django_nginx
    image: nginx:1.25.3-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./data/nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - static_volume:/thnz/static
      - media_volume:/thnz/media
    networks:
      - main_network

volumes:
  db_data:
  static_volume:
  media_volume:


networks:
  main_network:
